### ISSUE TITLE
Needs tabs permissions

### ISSUE THREAD

**Issue by trlkly** [ianhanniballake/ComicUpdater#11]
Chrome has changed how the tabs permissions works, and you need to enable it for your addon. It's a very simple fix: just add "tabs" to the permissions list in the manifest.json.

This has already been reported as an issue on the Chrome addon page, but I thought maybe you missed it. So I thought I'd post it here. 

(And, no, I am not James Kelley, but his instructions worked for me.)

**Comment by ianhanniballake** [comment]
Fixed in #12, TBD when the next release will be
